# Generated by Django 3.1.1 on 2021-08-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210803_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
