# Generated by Django 3.1.1 on 2021-08-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_is_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_changed',
            field=models.BooleanField(default=True),
        ),
    ]
