# Generated by Django 3.1.1 on 2021-07-08 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvideodata',
            name='last_watched',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 8, 46, 43, 744916, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='is_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 8, 46, 43, 744550, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='studentvideodata',
            unique_together={('student', 'video')},
        ),
    ]
