# Generated by Django 3.1.1 on 2021-07-27 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210708_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='link',
        ),
        migrations.AddField(
            model_name='videos',
            name='thumbnail',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='studentvideodata',
            name='last_watched',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 20, 43, 14, 132225, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='is_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 20, 43, 14, 131874, tzinfo=utc)),
        ),
    ]
