# Generated by Django 3.1.1 on 2021-07-27 20:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210728_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvideodata',
            name='last_watched',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 20, 45, 24, 490740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='is_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 20, 45, 24, 490415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='thumbnail',
            field=models.CharField(max_length=400),
        ),
    ]
