# Generated by Django 3.1.1 on 2021-07-28 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210728_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='average_viewtime',
            field=models.CharField(default=5, max_length=40),
        ),
        migrations.AddField(
            model_name='videos',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentvideodata',
            name='last_watched',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 14, 48, 54, 256801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='is_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 14, 48, 54, 256408, tzinfo=utc)),
        ),
    ]
