# Generated by Django 3.1.1 on 2021-07-28 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210728_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvideodata',
            name='last_watched',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 14, 51, 25, 527223, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='is_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 14, 51, 25, 526829, tzinfo=utc)),
        ),
    ]
