# Generated by Django 3.1.1 on 2021-07-28 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210728_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentvideodata',
            name='timelist',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentvideodata',
            name='last_watched',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 14, 58, 4, 185593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='is_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 14, 58, 4, 185191, tzinfo=utc)),
        ),
    ]
