# Generated by Django 3.1.1 on 2021-07-29 11:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210728_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvideodata',
            name='last_watched',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 11, 18, 35, 374792, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='videos',
            name='is_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 11, 18, 35, 374401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='thumbnail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
