# Generated by Django 3.1.1 on 2021-08-03 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210729_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvideodata',
            name='last_watched',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 11, 34, 14, 88738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='is_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 11, 34, 14, 88326, tzinfo=utc)),
        ),
    ]
