# Generated by Django 3.1.1 on 2021-08-04 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210803_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvideodata',
            name='last_watched',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 10, 7, 19, 276826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='average_viewtime',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='videos',
            name='is_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 10, 7, 19, 276298, tzinfo=utc)),
        ),
    ]
